#!/bin/bash
# ----------------------------------------------------------------------------
# 05 - Verify Deployments Cheatsheet
# ----------------------------------------------------------------------------
# Variables
APP_NAME="ai-api"
RG_NAME="rg-aca-demo"

# ----------------------------------------------------------------------------
# 1. Verify Application State
# Why: Check the macro-level ingress settings, FQDN, and base configuration.
# ----------------------------------------------------------------------------
az containerapp show \
  -n $APP_NAME \
  -g $RG_NAME

# ----------------------------------------------------------------------------
# 2. Verify Revisions
# Why: Confirm that a newly deployed update resulted in a healthy, active blueprint.
# ----------------------------------------------------------------------------
az containerapp revision list \
  -n $APP_NAME \
  -g $RG_NAME

# (Optional) See old inactive versions
# az containerapp revision list -n $APP_NAME -g $RG_NAME --all

# ----------------------------------------------------------------------------
# 3. Verify Replicas
# Why: Check if workers are stuck in a CrashLoopBackOff or scaled to zero.
# ----------------------------------------------------------------------------
az containerapp replica list \
  -n $APP_NAME \
  -g $RG_NAME

# ----------------------------------------------------------------------------
# 4. Logs - Console (App Code)
# Why: Stream live output generated by your actual application code to catch exceptions.
# ----------------------------------------------------------------------------
az containerapp logs show \
  -n $APP_NAME \
  -g $RG_NAME \
  --follow \
  --tail 30

# ----------------------------------------------------------------------------
# 5. Logs - System (Infrastructure)
# Why: Debug platform failures like container pull errors or out-of-memory kills.
# ----------------------------------------------------------------------------
az containerapp logs show \
  -n $APP_NAME \
  -g $RG_NAME \
  --type system
